query GetFeeds {
	feeds {
		id
		url
		title
		fetchedAt
		isSubscribed
		unreadCount
	}
}

query GetUnreadArticles($feedId: ID, $after: ID, $first: Int) {
	unreadArticles(feedId: $feedId, after: $after, first: $first) {
		articles {
			id
			feedId
			guid
			title
			url
			isRead
			feed {
				id
				title
				isSubscribed
			}
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}

query GetReadArticles($feedId: ID, $after: ID, $first: Int) {
	readArticles(feedId: $feedId, after: $after, first: $first) {
		articles {
			id
			feedId
			guid
			title
			url
			isRead
			feed {
				id
				title
				isSubscribed
			}
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}

query GetFeed($id: ID!) {
	feed(id: $id) {
		id
		url
		title
		fetchedAt
		isSubscribed
		articles {
			id
			guid
			title
			url
			isRead
		}
	}
}

query GetArticle($id: ID!) {
	article(id: $id) {
		id
		feedId
		guid
		title
		url
		isRead
		feed {
			id
			title
			isSubscribed
		}
	}
}

query GetCurrentUser {
	currentUser {
		id
		username
	}
}
