// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: feedaka.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeedakaService_GetFeeds_FullMethodName          = "/feedaka.v1.FeedakaService/GetFeeds"
	FeedakaService_AddFeed_FullMethodName           = "/feedaka.v1.FeedakaService/AddFeed"
	FeedakaService_RemoveFeed_FullMethodName        = "/feedaka.v1.FeedakaService/RemoveFeed"
	FeedakaService_GetUnreadArticles_FullMethodName = "/feedaka.v1.FeedakaService/GetUnreadArticles"
	FeedakaService_GetReadArticles_FullMethodName   = "/feedaka.v1.FeedakaService/GetReadArticles"
	FeedakaService_MarkArticleRead_FullMethodName   = "/feedaka.v1.FeedakaService/MarkArticleRead"
	FeedakaService_MarkArticleUnread_FullMethodName = "/feedaka.v1.FeedakaService/MarkArticleUnread"
	FeedakaService_MarkFeedRead_FullMethodName      = "/feedaka.v1.FeedakaService/MarkFeedRead"
	FeedakaService_MarkFeedUnread_FullMethodName    = "/feedaka.v1.FeedakaService/MarkFeedUnread"
)

// FeedakaServiceClient is the client API for FeedakaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedakaServiceClient interface {
	// Feeds
	GetFeeds(ctx context.Context, in *GetFeedsRequest, opts ...grpc.CallOption) (*GetFeedsResponse, error)
	AddFeed(ctx context.Context, in *AddFeedRequest, opts ...grpc.CallOption) (*AddFeedResponse, error)
	RemoveFeed(ctx context.Context, in *RemoveFeedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Articles
	GetUnreadArticles(ctx context.Context, in *GetUnreadArticlesRequest, opts ...grpc.CallOption) (*GetUnreadArticlesResponse, error)
	GetReadArticles(ctx context.Context, in *GetReadArticlesRequest, opts ...grpc.CallOption) (*GetReadArticlesResponse, error)
	// State management
	MarkArticleRead(ctx context.Context, in *MarkArticleReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MarkArticleUnread(ctx context.Context, in *MarkArticleUnreadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MarkFeedRead(ctx context.Context, in *MarkFeedReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MarkFeedUnread(ctx context.Context, in *MarkFeedUnreadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type feedakaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedakaServiceClient(cc grpc.ClientConnInterface) FeedakaServiceClient {
	return &feedakaServiceClient{cc}
}

func (c *feedakaServiceClient) GetFeeds(ctx context.Context, in *GetFeedsRequest, opts ...grpc.CallOption) (*GetFeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedsResponse)
	err := c.cc.Invoke(ctx, FeedakaService_GetFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedakaServiceClient) AddFeed(ctx context.Context, in *AddFeedRequest, opts ...grpc.CallOption) (*AddFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFeedResponse)
	err := c.cc.Invoke(ctx, FeedakaService_AddFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedakaServiceClient) RemoveFeed(ctx context.Context, in *RemoveFeedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FeedakaService_RemoveFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedakaServiceClient) GetUnreadArticles(ctx context.Context, in *GetUnreadArticlesRequest, opts ...grpc.CallOption) (*GetUnreadArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadArticlesResponse)
	err := c.cc.Invoke(ctx, FeedakaService_GetUnreadArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedakaServiceClient) GetReadArticles(ctx context.Context, in *GetReadArticlesRequest, opts ...grpc.CallOption) (*GetReadArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadArticlesResponse)
	err := c.cc.Invoke(ctx, FeedakaService_GetReadArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedakaServiceClient) MarkArticleRead(ctx context.Context, in *MarkArticleReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FeedakaService_MarkArticleRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedakaServiceClient) MarkArticleUnread(ctx context.Context, in *MarkArticleUnreadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FeedakaService_MarkArticleUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedakaServiceClient) MarkFeedRead(ctx context.Context, in *MarkFeedReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FeedakaService_MarkFeedRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedakaServiceClient) MarkFeedUnread(ctx context.Context, in *MarkFeedUnreadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FeedakaService_MarkFeedUnread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedakaServiceServer is the server API for FeedakaService service.
// All implementations must embed UnimplementedFeedakaServiceServer
// for forward compatibility.
type FeedakaServiceServer interface {
	// Feeds
	GetFeeds(context.Context, *GetFeedsRequest) (*GetFeedsResponse, error)
	AddFeed(context.Context, *AddFeedRequest) (*AddFeedResponse, error)
	RemoveFeed(context.Context, *RemoveFeedRequest) (*emptypb.Empty, error)
	// Articles
	GetUnreadArticles(context.Context, *GetUnreadArticlesRequest) (*GetUnreadArticlesResponse, error)
	GetReadArticles(context.Context, *GetReadArticlesRequest) (*GetReadArticlesResponse, error)
	// State management
	MarkArticleRead(context.Context, *MarkArticleReadRequest) (*emptypb.Empty, error)
	MarkArticleUnread(context.Context, *MarkArticleUnreadRequest) (*emptypb.Empty, error)
	MarkFeedRead(context.Context, *MarkFeedReadRequest) (*emptypb.Empty, error)
	MarkFeedUnread(context.Context, *MarkFeedUnreadRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFeedakaServiceServer()
}

// UnimplementedFeedakaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedakaServiceServer struct{}

func (UnimplementedFeedakaServiceServer) GetFeeds(context.Context, *GetFeedsRequest) (*GetFeedsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeeds not implemented")
}
func (UnimplementedFeedakaServiceServer) AddFeed(context.Context, *AddFeedRequest) (*AddFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFeed not implemented")
}
func (UnimplementedFeedakaServiceServer) RemoveFeed(context.Context, *RemoveFeedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFeed not implemented")
}
func (UnimplementedFeedakaServiceServer) GetUnreadArticles(context.Context, *GetUnreadArticlesRequest) (*GetUnreadArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadArticles not implemented")
}
func (UnimplementedFeedakaServiceServer) GetReadArticles(context.Context, *GetReadArticlesRequest) (*GetReadArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReadArticles not implemented")
}
func (UnimplementedFeedakaServiceServer) MarkArticleRead(context.Context, *MarkArticleReadRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkArticleRead not implemented")
}
func (UnimplementedFeedakaServiceServer) MarkArticleUnread(context.Context, *MarkArticleUnreadRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkArticleUnread not implemented")
}
func (UnimplementedFeedakaServiceServer) MarkFeedRead(context.Context, *MarkFeedReadRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkFeedRead not implemented")
}
func (UnimplementedFeedakaServiceServer) MarkFeedUnread(context.Context, *MarkFeedUnreadRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkFeedUnread not implemented")
}
func (UnimplementedFeedakaServiceServer) mustEmbedUnimplementedFeedakaServiceServer() {}
func (UnimplementedFeedakaServiceServer) testEmbeddedByValue()                        {}

// UnsafeFeedakaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedakaServiceServer will
// result in compilation errors.
type UnsafeFeedakaServiceServer interface {
	mustEmbedUnimplementedFeedakaServiceServer()
}

func RegisterFeedakaServiceServer(s grpc.ServiceRegistrar, srv FeedakaServiceServer) {
	// If the following call pancis, it indicates UnimplementedFeedakaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedakaService_ServiceDesc, srv)
}

func _FeedakaService_GetFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedakaServiceServer).GetFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedakaService_GetFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedakaServiceServer).GetFeeds(ctx, req.(*GetFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedakaService_AddFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedakaServiceServer).AddFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedakaService_AddFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedakaServiceServer).AddFeed(ctx, req.(*AddFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedakaService_RemoveFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedakaServiceServer).RemoveFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedakaService_RemoveFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedakaServiceServer).RemoveFeed(ctx, req.(*RemoveFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedakaService_GetUnreadArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedakaServiceServer).GetUnreadArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedakaService_GetUnreadArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedakaServiceServer).GetUnreadArticles(ctx, req.(*GetUnreadArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedakaService_GetReadArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedakaServiceServer).GetReadArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedakaService_GetReadArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedakaServiceServer).GetReadArticles(ctx, req.(*GetReadArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedakaService_MarkArticleRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkArticleReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedakaServiceServer).MarkArticleRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedakaService_MarkArticleRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedakaServiceServer).MarkArticleRead(ctx, req.(*MarkArticleReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedakaService_MarkArticleUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkArticleUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedakaServiceServer).MarkArticleUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedakaService_MarkArticleUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedakaServiceServer).MarkArticleUnread(ctx, req.(*MarkArticleUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedakaService_MarkFeedRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkFeedReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedakaServiceServer).MarkFeedRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedakaService_MarkFeedRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedakaServiceServer).MarkFeedRead(ctx, req.(*MarkFeedReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedakaService_MarkFeedUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkFeedUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedakaServiceServer).MarkFeedUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedakaService_MarkFeedUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedakaServiceServer).MarkFeedUnread(ctx, req.(*MarkFeedUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedakaService_ServiceDesc is the grpc.ServiceDesc for FeedakaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedakaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feedaka.v1.FeedakaService",
	HandlerType: (*FeedakaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeeds",
			Handler:    _FeedakaService_GetFeeds_Handler,
		},
		{
			MethodName: "AddFeed",
			Handler:    _FeedakaService_AddFeed_Handler,
		},
		{
			MethodName: "RemoveFeed",
			Handler:    _FeedakaService_RemoveFeed_Handler,
		},
		{
			MethodName: "GetUnreadArticles",
			Handler:    _FeedakaService_GetUnreadArticles_Handler,
		},
		{
			MethodName: "GetReadArticles",
			Handler:    _FeedakaService_GetReadArticles_Handler,
		},
		{
			MethodName: "MarkArticleRead",
			Handler:    _FeedakaService_MarkArticleRead_Handler,
		},
		{
			MethodName: "MarkArticleUnread",
			Handler:    _FeedakaService_MarkArticleUnread_Handler,
		},
		{
			MethodName: "MarkFeedRead",
			Handler:    _FeedakaService_MarkFeedRead_Handler,
		},
		{
			MethodName: "MarkFeedUnread",
			Handler:    _FeedakaService_MarkFeedUnread_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedaka.proto",
}
