// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: feedaka.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Feed
type Feed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_feedaka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{0}
}

func (x *Feed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Feed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Feed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feed) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *Feed) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// Article
type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FeedId        int32                  `protobuf:"varint,2,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Guid          string                 `protobuf:"bytes,3,opt,name=guid,proto3" json:"guid,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	IsRead        bool                   `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	Feed          *Feed                  `protobuf:"bytes,7,opt,name=feed,proto3" json:"feed,omitempty"` // Optional: populated when needed for context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_feedaka_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{1}
}

func (x *Article) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetFeedId() int32 {
	if x != nil {
		return x.FeedId
	}
	return 0
}

func (x *Article) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Article) GetFeed() *Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

type GetFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedsRequest) Reset() {
	*x = GetFeedsRequest{}
	mi := &file_feedaka_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedsRequest) ProtoMessage() {}

func (x *GetFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedsRequest.ProtoReflect.Descriptor instead.
func (*GetFeedsRequest) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{2}
}

type GetFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*Feed                `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedsResponse) Reset() {
	*x = GetFeedsResponse{}
	mi := &file_feedaka_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedsResponse) ProtoMessage() {}

func (x *GetFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedsResponse.ProtoReflect.Descriptor instead.
func (*GetFeedsResponse) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeedsResponse) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

type GetUnreadArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Optional: default 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadArticlesRequest) Reset() {
	*x = GetUnreadArticlesRequest{}
	mi := &file_feedaka_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadArticlesRequest) ProtoMessage() {}

func (x *GetUnreadArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadArticlesRequest) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{4}
}

func (x *GetUnreadArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUnreadArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadArticlesResponse) Reset() {
	*x = GetUnreadArticlesResponse{}
	mi := &file_feedaka_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadArticlesResponse) ProtoMessage() {}

func (x *GetUnreadArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadArticlesResponse) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{5}
}

func (x *GetUnreadArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type GetReadArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Optional: default 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadArticlesRequest) Reset() {
	*x = GetReadArticlesRequest{}
	mi := &file_feedaka_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadArticlesRequest) ProtoMessage() {}

func (x *GetReadArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetReadArticlesRequest) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{6}
}

func (x *GetReadArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetReadArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadArticlesResponse) Reset() {
	*x = GetReadArticlesResponse{}
	mi := &file_feedaka_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadArticlesResponse) ProtoMessage() {}

func (x *GetReadArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetReadArticlesResponse) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{7}
}

func (x *GetReadArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type AddFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedRequest) Reset() {
	*x = AddFeedRequest{}
	mi := &file_feedaka_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedRequest) ProtoMessage() {}

func (x *AddFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedRequest.ProtoReflect.Descriptor instead.
func (*AddFeedRequest) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{8}
}

func (x *AddFeedRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feed          *Feed                  `protobuf:"bytes,1,opt,name=feed,proto3" json:"feed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedResponse) Reset() {
	*x = AddFeedResponse{}
	mi := &file_feedaka_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedResponse) ProtoMessage() {}

func (x *AddFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedResponse.ProtoReflect.Descriptor instead.
func (*AddFeedResponse) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{9}
}

func (x *AddFeedResponse) GetFeed() *Feed {
	if x != nil {
		return x.Feed
	}
	return nil
}

type RemoveFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFeedRequest) Reset() {
	*x = RemoveFeedRequest{}
	mi := &file_feedaka_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFeedRequest) ProtoMessage() {}

func (x *RemoveFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFeedRequest.ProtoReflect.Descriptor instead.
func (*RemoveFeedRequest) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveFeedRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MarkArticleReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkArticleReadRequest) Reset() {
	*x = MarkArticleReadRequest{}
	mi := &file_feedaka_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkArticleReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkArticleReadRequest) ProtoMessage() {}

func (x *MarkArticleReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkArticleReadRequest.ProtoReflect.Descriptor instead.
func (*MarkArticleReadRequest) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{11}
}

func (x *MarkArticleReadRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MarkArticleUnreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkArticleUnreadRequest) Reset() {
	*x = MarkArticleUnreadRequest{}
	mi := &file_feedaka_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkArticleUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkArticleUnreadRequest) ProtoMessage() {}

func (x *MarkArticleUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkArticleUnreadRequest.ProtoReflect.Descriptor instead.
func (*MarkArticleUnreadRequest) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{12}
}

func (x *MarkArticleUnreadRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MarkFeedReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkFeedReadRequest) Reset() {
	*x = MarkFeedReadRequest{}
	mi := &file_feedaka_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkFeedReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFeedReadRequest) ProtoMessage() {}

func (x *MarkFeedReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFeedReadRequest.ProtoReflect.Descriptor instead.
func (*MarkFeedReadRequest) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{13}
}

func (x *MarkFeedReadRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MarkFeedUnreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkFeedUnreadRequest) Reset() {
	*x = MarkFeedUnreadRequest{}
	mi := &file_feedaka_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkFeedUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFeedUnreadRequest) ProtoMessage() {}

func (x *MarkFeedUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaka_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFeedUnreadRequest.ProtoReflect.Descriptor instead.
func (*MarkFeedUnreadRequest) Descriptor() ([]byte, []int) {
	return file_feedaka_proto_rawDescGZIP(), []int{14}
}

func (x *MarkFeedUnreadRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_feedaka_proto protoreflect.FileDescriptor

const file_feedaka_proto_rawDesc = "" +
	"\n" +
	"\rfeedaka.proto\x12\n" +
	"feedaka.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9c\x01\n" +
	"\x04Feed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x129\n" +
	"\n" +
	"fetched_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x12!\n" +
	"\funread_count\x18\x05 \x01(\x05R\vunreadCount\"\xad\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\afeed_id\x18\x02 \x01(\x05R\x06feedId\x12\x12\n" +
	"\x04guid\x18\x03 \x01(\tR\x04guid\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x17\n" +
	"\ais_read\x18\x06 \x01(\bR\x06isRead\x12$\n" +
	"\x04feed\x18\a \x01(\v2\x10.feedaka.v1.FeedR\x04feed\"\x11\n" +
	"\x0fGetFeedsRequest\":\n" +
	"\x10GetFeedsResponse\x12&\n" +
	"\x05feeds\x18\x01 \x03(\v2\x10.feedaka.v1.FeedR\x05feeds\"0\n" +
	"\x18GetUnreadArticlesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"L\n" +
	"\x19GetUnreadArticlesResponse\x12/\n" +
	"\barticles\x18\x01 \x03(\v2\x13.feedaka.v1.ArticleR\barticles\".\n" +
	"\x16GetReadArticlesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"J\n" +
	"\x17GetReadArticlesResponse\x12/\n" +
	"\barticles\x18\x01 \x03(\v2\x13.feedaka.v1.ArticleR\barticles\"\"\n" +
	"\x0eAddFeedRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"7\n" +
	"\x0fAddFeedResponse\x12$\n" +
	"\x04feed\x18\x01 \x01(\v2\x10.feedaka.v1.FeedR\x04feed\"#\n" +
	"\x11RemoveFeedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"(\n" +
	"\x16MarkArticleReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"*\n" +
	"\x18MarkArticleUnreadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"%\n" +
	"\x13MarkFeedReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"'\n" +
	"\x15MarkFeedUnreadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xd6\x05\n" +
	"\x0eFeedakaService\x12E\n" +
	"\bGetFeeds\x12\x1b.feedaka.v1.GetFeedsRequest\x1a\x1c.feedaka.v1.GetFeedsResponse\x12B\n" +
	"\aAddFeed\x12\x1a.feedaka.v1.AddFeedRequest\x1a\x1b.feedaka.v1.AddFeedResponse\x12C\n" +
	"\n" +
	"RemoveFeed\x12\x1d.feedaka.v1.RemoveFeedRequest\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\x11GetUnreadArticles\x12$.feedaka.v1.GetUnreadArticlesRequest\x1a%.feedaka.v1.GetUnreadArticlesResponse\x12Z\n" +
	"\x0fGetReadArticles\x12\".feedaka.v1.GetReadArticlesRequest\x1a#.feedaka.v1.GetReadArticlesResponse\x12M\n" +
	"\x0fMarkArticleRead\x12\".feedaka.v1.MarkArticleReadRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x11MarkArticleUnread\x12$.feedaka.v1.MarkArticleUnreadRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\fMarkFeedRead\x12\x1f.feedaka.v1.MarkFeedReadRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x0eMarkFeedUnread\x12!.feedaka.v1.MarkFeedUnreadRequest\x1a\x16.google.protobuf.EmptyB.Z,github.com/nsfisis/feedaka/backend/grpc;grpcb\x06proto3"

var (
	file_feedaka_proto_rawDescOnce sync.Once
	file_feedaka_proto_rawDescData []byte
)

func file_feedaka_proto_rawDescGZIP() []byte {
	file_feedaka_proto_rawDescOnce.Do(func() {
		file_feedaka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedaka_proto_rawDesc), len(file_feedaka_proto_rawDesc)))
	})
	return file_feedaka_proto_rawDescData
}

var file_feedaka_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_feedaka_proto_goTypes = []any{
	(*Feed)(nil),                      // 0: feedaka.v1.Feed
	(*Article)(nil),                   // 1: feedaka.v1.Article
	(*GetFeedsRequest)(nil),           // 2: feedaka.v1.GetFeedsRequest
	(*GetFeedsResponse)(nil),          // 3: feedaka.v1.GetFeedsResponse
	(*GetUnreadArticlesRequest)(nil),  // 4: feedaka.v1.GetUnreadArticlesRequest
	(*GetUnreadArticlesResponse)(nil), // 5: feedaka.v1.GetUnreadArticlesResponse
	(*GetReadArticlesRequest)(nil),    // 6: feedaka.v1.GetReadArticlesRequest
	(*GetReadArticlesResponse)(nil),   // 7: feedaka.v1.GetReadArticlesResponse
	(*AddFeedRequest)(nil),            // 8: feedaka.v1.AddFeedRequest
	(*AddFeedResponse)(nil),           // 9: feedaka.v1.AddFeedResponse
	(*RemoveFeedRequest)(nil),         // 10: feedaka.v1.RemoveFeedRequest
	(*MarkArticleReadRequest)(nil),    // 11: feedaka.v1.MarkArticleReadRequest
	(*MarkArticleUnreadRequest)(nil),  // 12: feedaka.v1.MarkArticleUnreadRequest
	(*MarkFeedReadRequest)(nil),       // 13: feedaka.v1.MarkFeedReadRequest
	(*MarkFeedUnreadRequest)(nil),     // 14: feedaka.v1.MarkFeedUnreadRequest
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 16: google.protobuf.Empty
}
var file_feedaka_proto_depIdxs = []int32{
	15, // 0: feedaka.v1.Feed.fetched_at:type_name -> google.protobuf.Timestamp
	0,  // 1: feedaka.v1.Article.feed:type_name -> feedaka.v1.Feed
	0,  // 2: feedaka.v1.GetFeedsResponse.feeds:type_name -> feedaka.v1.Feed
	1,  // 3: feedaka.v1.GetUnreadArticlesResponse.articles:type_name -> feedaka.v1.Article
	1,  // 4: feedaka.v1.GetReadArticlesResponse.articles:type_name -> feedaka.v1.Article
	0,  // 5: feedaka.v1.AddFeedResponse.feed:type_name -> feedaka.v1.Feed
	2,  // 6: feedaka.v1.FeedakaService.GetFeeds:input_type -> feedaka.v1.GetFeedsRequest
	8,  // 7: feedaka.v1.FeedakaService.AddFeed:input_type -> feedaka.v1.AddFeedRequest
	10, // 8: feedaka.v1.FeedakaService.RemoveFeed:input_type -> feedaka.v1.RemoveFeedRequest
	4,  // 9: feedaka.v1.FeedakaService.GetUnreadArticles:input_type -> feedaka.v1.GetUnreadArticlesRequest
	6,  // 10: feedaka.v1.FeedakaService.GetReadArticles:input_type -> feedaka.v1.GetReadArticlesRequest
	11, // 11: feedaka.v1.FeedakaService.MarkArticleRead:input_type -> feedaka.v1.MarkArticleReadRequest
	12, // 12: feedaka.v1.FeedakaService.MarkArticleUnread:input_type -> feedaka.v1.MarkArticleUnreadRequest
	13, // 13: feedaka.v1.FeedakaService.MarkFeedRead:input_type -> feedaka.v1.MarkFeedReadRequest
	14, // 14: feedaka.v1.FeedakaService.MarkFeedUnread:input_type -> feedaka.v1.MarkFeedUnreadRequest
	3,  // 15: feedaka.v1.FeedakaService.GetFeeds:output_type -> feedaka.v1.GetFeedsResponse
	9,  // 16: feedaka.v1.FeedakaService.AddFeed:output_type -> feedaka.v1.AddFeedResponse
	16, // 17: feedaka.v1.FeedakaService.RemoveFeed:output_type -> google.protobuf.Empty
	5,  // 18: feedaka.v1.FeedakaService.GetUnreadArticles:output_type -> feedaka.v1.GetUnreadArticlesResponse
	7,  // 19: feedaka.v1.FeedakaService.GetReadArticles:output_type -> feedaka.v1.GetReadArticlesResponse
	16, // 20: feedaka.v1.FeedakaService.MarkArticleRead:output_type -> google.protobuf.Empty
	16, // 21: feedaka.v1.FeedakaService.MarkArticleUnread:output_type -> google.protobuf.Empty
	16, // 22: feedaka.v1.FeedakaService.MarkFeedRead:output_type -> google.protobuf.Empty
	16, // 23: feedaka.v1.FeedakaService.MarkFeedUnread:output_type -> google.protobuf.Empty
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_feedaka_proto_init() }
func file_feedaka_proto_init() {
	if File_feedaka_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedaka_proto_rawDesc), len(file_feedaka_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedaka_proto_goTypes,
		DependencyIndexes: file_feedaka_proto_depIdxs,
		MessageInfos:      file_feedaka_proto_msgTypes,
	}.Build()
	File_feedaka_proto = out.File
	file_feedaka_proto_goTypes = nil
	file_feedaka_proto_depIdxs = nil
}
