// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Article struct {
	ID     int64
	FeedID int64
	Guid   string
	Title  string
	Url    string
	IsRead int64
}

type Feed struct {
	ID           int64
	Url          string
	Title        string
	FetchedAt    string
	IsSubscribed int64
	UserID       int64
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    string
}
